name: 'Auto set label "approve" after merge'

on:
  pull_request:
    branches: [ "master" ]
    types: [closed]

jobs:
  add-label:
    name: "Auto set label 'approve'"
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Add label 'approve' to pull-request
        uses: andymckay/labeler@master
        with:
          remove-labels: "awaiting review"
          add-labels: "approve"
