name: Backend Production Unit Tests

on:
  workflow_run:
    workflows: [Docker Compose Deploy]
    types: [completed]

jobs:
  http-production-clients-test:
    name: HttpClients Production Unit Test
    runs-on: ubuntu-latest
    env:
      ProjectName: HeadHunter.HttpClients.Tests
      OnlyTests: HeadHunter.HttpClients.Tests.Resource
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET

      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore $ProjectName

    - name: Build
      run: dotnet build $ProjectName --no-restore

    - name: Test
      run: dotnet test $ProjectName --no-build -l "console;verbosity=normal" --filter FullyQualifiedName~$OnlyTests