name: Docker Compose Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Docker Compose Deploy
    runs-on: ubuntu-latest
    env:
      DOCKER_NAME: headhunter
      DOCKER_IMAGE: docker.pkg.github.com/Lev4and/${GITHUB_REPOSITORY##*/}/${DOCKER_NAME}:${GITHUB_REF##*/}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to docker.pkg.github.com
      run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

    - name: Copy .env.dist file
      run: cp .env.dist .env

    - name: Export .env file
      run: export $(egrep -v '^#' .env | xargs -0)

    - name: Create volume for docker containers
      run: |
        docker volume create portainer_data
        docker volume create grafana_data
    
    - name: Build docker compose image
      run: docker compose -f docker-compose.yml build

    - name: Push docker compose image
      run: docker compose -f docker-compose.yml push