name: Docker Compose Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  headhunter-vuejsapp-build:
    name: headhunter-vuejsapp image build and push
    runs-on: ubuntu-latest
    env:
      PROJECT_SRC_DIR: head-hunter-vue-js-app
      DOCKER_NAME: headhuntervuejsapp
      DOCKER_IMAGE: docker.pkg.github.com/lev4and/headhunter/headhuntervuejsapp
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to docker.pkg.github.com
        run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build and pull docker image
        run: docker build -f Dockerfile --pull -t $DOCKER_IMAGE $PROJECT_SRC_DIR

      - name: Push docker image
        run: docker push $DOCKER_IMAGE

  headhunter-authorizationwebapplication-build:
    name: headhunter-authorizationwebapplication image build and push
    runs-on: ubuntu-latest
    env:
      PROJECT_SRC_DIR: HeadHunter.AuthorizationWebApplication
      DOCKER_NAME: headhunterauthorizationwebapplication
      DOCKER_IMAGE: docker.pkg.github.com/lev4and/headhunter/headhunterauthorizationwebapplication
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to docker.pkg.github.com
        run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build and pull docker image
        run: docker build -f Dockerfile --pull -t $DOCKER_IMAGE $PROJECT_SRC_DIR

      - name: Push docker image
        run: docker push $DOCKER_IMAGE

  headhunter-resourcewebapplication-build:
    name: headhunter-resourcewebapplication image build and push
    runs-on: ubuntu-latest
    env:
      PROJECT_SRC_DIR: HeadHunter.ResourceWebApplication
      DOCKER_NAME: headhunterresourcewebapplication
      DOCKER_IMAGE: docker.pkg.github.com/lev4and/headhunter/headhunterresourcewebapplication
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to docker.pkg.github.com
        run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build and pull docker image
        run: docker build -f Dockerfile --pull -t $DOCKER_IMAGE $PROJECT_SRC_DIR

      - name: Push docker image
        run: docker push $DOCKER_IMAGE