name: Docker Compose Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Docker Compose Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and push image
      run: |
        DOCKER_NAME=headhunter
        DOCKER_IMAGE=docker.pkg.github.com/Lev4and/${GITHUB_REPOSITORY##*/}/${DOCKER_NAME}:${GITHUB_REF##*/}
        docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
        rm .env
        cp .env.dist .env
        export $(egrep -v '^#' .env | xargs -0)
        docker volume create portainer_data
        docker volume create grafana_data
        docker-compose up $DOCKER_IMAGE
        docker-compose push $DOCKER_IMAGE